import type { MetadataRoute } from "next";

// Robots.txt auto-generated by Next.js App Router
// Instructs search engine crawlers on what to index
// NOTE: With output: 'export', this generates a static robots.txt file

export default function robots(): MetadataRoute.Robots {
  const siteUrl = "https://maqas.site";

  return {
    rules: [
      {
        // Allow all major search engines to index public pages
        userAgent: [
          "Googlebot",
          "Bingbot",
          "Slurp",
          "DuckDuckBot",
          "Baiduspider",
          "YandexBot",
        ],
        allow: "/",
        disallow: [
          "/admin/",
          "/superadmin/",
          "/api/",
          "/employee/",
        ],
      },
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/admin/", "/superadmin/", "/api/", "/employee/"],
      },
    ],
    sitemap: `${siteUrl}/sitemap.xml`,
    host: siteUrl,
  };
}
