import type { MetadataRoute } from "next";

// XML Sitemap auto-generated by Next.js App Router
// Submitted to Google Search Console for better indexing

/** يجب أن يطابق المضيف الكنسي `metadataBase` في layout (بدون www) لتوحيد فهرسة Google. */
export default function sitemap(): MetadataRoute.Sitemap {
  const siteUrl = "https://maqas.site";
  const now = new Date();

  return [
    {
      url: `${siteUrl}/`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${siteUrl}/book/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: `${siteUrl}/contact/`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${siteUrl}/login/`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${siteUrl}/privacy/`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.35,
    },
    {
      url: `${siteUrl}/terms/`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.35,
    },
  ];
}
